### ISSUE TITLE
node_modules not included in Lambda ZIP

### ISSUE THREAD

**Issue by uriahcarpenter** [Widen/cloudfront-auth#10] opened 2018-05-08 23:07 UTC
Using node `v7.10.1`, npm `v4.2.0` (via Node Version Mananger)

A previously generated ZIP was ~481 KB, using master/HEAD it's now 8 K. Appears that `node_modules` is no longer being included in the ZIP.

(I'm not sure how to get NPM 5.6 with Node 7 via NVM. Maybe update to Node 8 (lts/carbon)?)

**Comment by payton** [comment] 2018-05-11 21:30
Issue caused by symlink. Zip was not including files in root project folder after moving to distributions directory. Fixed in cb2ae8b0c8e8d3d69a250e1bebffec5925fdec23

**Closed by payton** 2018-05-11 21:30 UTC
